CC = gcc
CFLAGS = -O3 -Wall

QS_Secuencial: QS_Secuencial.c
	$(CC) $(CFLAGS) -o QS_Secuencial QS_Secuencial.c

run: QS_Secuencial
	./QS_Secuencial 300000000 2

clean: QS_Secuencial
	rm QS_Secuencial

